<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.3.2 (Python 3.12.4 on win32)" generated="2025-08-19T16:13:24.935238" rpa="false" schemaversion="5">
<suite id="s1" name="MobileTests" source="C:\Users\shant\MobileTests">
<suite id="s1-s1" name="Open Wifi" source="C:\Users\shant\MobileTests\open_wifi.robot">
<test id="s1-s1-t1" name="Open Application" line="14">
<kw name="Open Application" owner="AppiumLibrary">
<msg time="2025-08-19T16:13:29.599337" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002B2B38BE780&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session</msg>
<msg time="2025-08-19T16:13:33.697597" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002B2B3789910&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session</msg>
<msg time="2025-08-19T16:13:37.823800" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002B2B38BFDA0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session</msg>
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2025-08-19T16:13:41.913825" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2025-08-19T16:13:41.912826" elapsed="0.036275">No application is open</status>
</kw>
<msg time="2025-08-19T16:13:41.951305" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2025-08-19T16:13:41.980548" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002B2B38E0320&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</msg>
<arg>${REMOTE_URL}</arg>
<arg>platformName=${PLATFORM_NAME}</arg>
<arg>platformVersion=${PLATFORM_VERSION}</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>automationName=${AUTOMATION_NAME}</arg>
<arg>appPackage=${APP_PACKAGE}</arg>
<arg>appActivity=${APP_ACTIVITY}</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://appium.io/docs/en/2.19/guides/caps/
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | No     | alias             |</doc>
<status status="FAIL" start="2025-08-19T16:13:25.540003" elapsed="16.449541">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002B2B38E0320&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</status>
</kw>
<kw name="Sleep" owner="BuiltIn">
<arg>3s</arg>
<doc>Pauses the test executed for the given time.</doc>
<status status="NOT RUN" start="2025-08-19T16:13:41.990544" elapsed="0.000000"/>
</kw>
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="NOT RUN" start="2025-08-19T16:13:41.990544" elapsed="0.000000"/>
</kw>
<kw name="Close Application" owner="AppiumLibrary">
<doc>Closes the current application and also close webdriver session.</doc>
<status status="NOT RUN" start="2025-08-19T16:13:41.990544" elapsed="0.000997"/>
</kw>
<status status="FAIL" start="2025-08-19T16:13:25.532848" elapsed="16.458693">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002B2B38E0320&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</status>
</test>
<status status="FAIL" start="2025-08-19T16:13:24.984169" elapsed="17.168891"/>
</suite>
<status status="FAIL" start="2025-08-19T16:13:24.942464" elapsed="17.225305"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat name="MobileTests" id="s1" pass="0" fail="1" skip="0">MobileTests</stat>
<stat name="Open Wifi" id="s1-s1" pass="0" fail="1" skip="0">MobileTests.Open Wifi</stat>
</suite>
</statistics>
<errors>
<msg time="2025-08-19T16:13:29.599337" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002B2B38BE780&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session</msg>
<msg time="2025-08-19T16:13:33.697597" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002B2B3789910&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session</msg>
<msg time="2025-08-19T16:13:37.823800" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002B2B38BFDA0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session</msg>
<msg time="2025-08-19T16:13:41.951305" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
